### ISSUE TITLE
Old API URLs will still work, but not for long - will be supported for 2 more months, after which they'll be disabled

### ISSUE THREAD

**Issue by danleyb2** [miguelcdpmarques/python-snovio#2]
Screenshot from Snov Telegram [channel](https://t.me/snovioupdates)

![2020-04-21_12-39](https://user-images.githubusercontent.com/9919961/79851016-6983c880-83cd-11ea-9420-d17bea672252.png)

[Current API documentation with new urls](https://snov.io/api)

[Outdated API documentation with old urls from Wayback machine]( https://web.archive.org/web/20200214062857/https://snov.io/api)

**Comment by miguelcdpmarques** [comment]
Thanks for providing the links to the previous and new endpoints! I've updated the wrapper and it should be working fine now.
