### ISSUE TITLE
Integration seems to have broken

### ISSUE THREAD

**Issue by dtquandt** [miguelcdpmarques/python-snovio#3]
It is no longer possible to create the API object with the client ID and secret, an error is thrown when calling json.loads(). Doing it with the access key seems to still work, or at least no error is thrown, but then it breaks when trying a request with an "argument of type 'NoneType' is not iterable" error.

**Comment by miguelcdpmarques** [comment]
Thanks for opening the issue. I've heard their API has changed recently so it might have broken the wrapper. 

I'll try to take a look at the changes from their side and update the API as soon as possible.

Pull requests are also welcome :)

**Comment by miguelcdpmarques** [comment]
I've updated the API wrapper to work on the new endpoints! Please re-open this issue if it fails for some reason.
